kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:token-exchange:agent
  namespace: {{ .ClusterName }}
rules:
- apiGroups: ["addon.open-cluster-management.io"]
  resources: ["managedclusteraddons"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["addon.open-cluster-management.io"]
  resources: ["managedclusteraddons/finalizers"]
  verbs: ["update"]
- apiGroups: ["addon.open-cluster-management.io"]
  resources: ["managedclusteraddons/status"]
  verbs: ["patch", "update"]