apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-exchange-agent-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["ceph.rook.io"]
  resources: ["cephclusters"]
  verbs: ["get", "list"]
- apiGroups: ["ocs.openshift.io"]
  resources: ["storageclusters"]
  verbs: ["get", "update"]
- apiGroups: ["replication.storage.openshift.io"]
  resources: ["volumereplicationclasses"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["objectbucket.io"]
  resources: ["objectbucketclaims"]
  verbs: ["get", "create",]
- apiGroups: ["multicluster.odf.openshift.io"]
  resources: ["mirrorpeers"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get","list","update"]