apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-exchange-agent-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["ceph.rook.io"]
  resources: ["cephclusters"]
  verbs: ["get", "list"]
- apiGroups: ["ocs.openshift.io"]
  resources: ["storageclusters"]
  verbs: ["get", "update"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list"]