kind: Deployment
apiVersion: apps/v1
metadata:
  name: token-exchange-agent
  namespace: {{ .AddonInstallNamespace }}
  labels:
    app: token-exchange-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token-exchange-agent
  template:
    metadata:
      labels:
        app: token-exchange-agent
    spec:
      serviceAccountName: token-exchange-agent-sa
      volumes:
      - name: hub-config
        secret:
          secretName: {{ .KubeConfigSecret }}
      containers:
      - name: token-exchange-agent
        image: {{ .Image }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          failureThreshold: 3
          periodSeconds: 30
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          failureThreshold: 3
          periodSeconds: 30
          initialDelaySeconds: 60
        command:
        - "/manager"
        args:
          - "addons"
          - "--hub-kubeconfig=/var/run/hub/kubeconfig"
          - "--cluster-name={{ .ClusterName }}"
          - "--mode={{ .DRMode }}"
        volumeMounts:
          - name: hub-config
            mountPath: /var/run/hub
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
